/*
  Generated by GBMB v1.8
*/
#include <stdint.h>
#include "takuzu_tiles.h"
#include "menu.h"

#define __ 27

const uint16_t menu_palette[] = {
    takuzu_tilesCGBPal3c0, takuzu_tilesCGBPal3c1,
    takuzu_tilesCGBPal3c2, takuzu_tilesCGBPal3c3,
    takuzu_tilesCGBPal3c0, 0, 0, takuzu_tilesCGBPal7c3,
    takuzu_tilesCGBPal3c0, takuzu_tilesCGBPal3c0, takuzu_tilesCGBPal3c0, takuzu_tilesCGBPal3c0
};

unsigned char menu_highscore[] =
{
  7, 8, 6, 7,__,18, 2,14,17, 4,
};

unsigned char menu_text[] =
{
  15,11, 0,24,__,__,__,__,
  __,__,__,__,__,__,__,__,
  15, 0,18,18,22,14,17, 3,
  __,__,__,__,__,__,__,__,
  14,15,19, 8,14,13,18,__,
  __,__,__,__,__,__,__,__,
   7, 4,11,15,__,__,__,__,
};

