/*

 TAKUZU_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 28

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define takuzu_tilesBank 0

/* Super Gameboy palette 0 */
#define takuzu_tilesSGBPal0c0 6076
#define takuzu_tilesSGBPal0c1 8935
#define takuzu_tilesSGBPal0c2 6596
#define takuzu_tilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define takuzu_tilesSGBPal1c0 6076
#define takuzu_tilesSGBPal1c1 8935
#define takuzu_tilesSGBPal1c2 6596
#define takuzu_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define takuzu_tilesSGBPal2c0 6076
#define takuzu_tilesSGBPal2c1 8935
#define takuzu_tilesSGBPal2c2 6596
#define takuzu_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define takuzu_tilesSGBPal3c0 6076
#define takuzu_tilesSGBPal3c1 8935
#define takuzu_tilesSGBPal3c2 6596
#define takuzu_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define takuzu_tilesCGBPal0c0 21140
#define takuzu_tilesCGBPal0c1 8456
#define takuzu_tilesCGBPal0c2 12684
#define takuzu_tilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define takuzu_tilesCGBPal1c0 21140
#define takuzu_tilesCGBPal1c1 29576
#define takuzu_tilesCGBPal1c2 12684
#define takuzu_tilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define takuzu_tilesCGBPal2c0 21140
#define takuzu_tilesCGBPal2c1 20988
#define takuzu_tilesCGBPal2c2 12684
#define takuzu_tilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define takuzu_tilesCGBPal3c0 21140
#define takuzu_tilesCGBPal3c1 16912
#define takuzu_tilesCGBPal3c2 12684
#define takuzu_tilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define takuzu_tilesCGBPal4c0 29596
#define takuzu_tilesCGBPal4c1 16912
#define takuzu_tilesCGBPal4c2 12684
#define takuzu_tilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define takuzu_tilesCGBPal5c0 8476
#define takuzu_tilesCGBPal5c1 16912
#define takuzu_tilesCGBPal5c2 12684
#define takuzu_tilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define takuzu_tilesCGBPal6c0 4228
#define takuzu_tilesCGBPal6c1 16912
#define takuzu_tilesCGBPal6c2 12684
#define takuzu_tilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define takuzu_tilesCGBPal7c0 1057*20
#define takuzu_tilesCGBPal7c1 1057*23
#define takuzu_tilesCGBPal7c2 1057*17
#define takuzu_tilesCGBPal7c3 1057*14

/*
BLUE-PINK
#define takuzu_tilesCGBPal7c0 21140
#define takuzu_tilesCGBPal7c1 30640
#define takuzu_tilesCGBPal7c2 25277
#define takuzu_tilesCGBPal7c3 6342
*/

/* Start of tile array. */
extern unsigned char takuzu_tiles_compressed[];

/* End of TAKUZU_TILES.H */
