/*

 TAKUZU_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define sprites_tilesBank 0

/* Super Gameboy palette 0 */
#define sprites_tilesSGBPal0c0 6076
#define sprites_tilesSGBPal0c1 8935
#define sprites_tilesSGBPal0c2 6596
#define sprites_tilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define sprites_tilesSGBPal1c0 6076
#define sprites_tilesSGBPal1c1 8935
#define sprites_tilesSGBPal1c2 6596
#define sprites_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define sprites_tilesSGBPal2c0 6076
#define sprites_tilesSGBPal2c1 8935
#define sprites_tilesSGBPal2c2 6596
#define sprites_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define sprites_tilesSGBPal3c0 6076
#define sprites_tilesSGBPal3c1 8935
#define sprites_tilesSGBPal3c2 6596
#define sprites_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define sprites_tilesCGBPal0c0 32361
#define sprites_tilesCGBPal0c1 32767
#define sprites_tilesCGBPal0c2 8456
#define sprites_tilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define sprites_tilesCGBPal1c0 32361
#define sprites_tilesCGBPal1c1 8479
#define sprites_tilesCGBPal1c2 8456
#define sprites_tilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define sprites_tilesCGBPal2c0 32361
#define sprites_tilesCGBPal2c1 8456
#define sprites_tilesCGBPal2c2 8456
#define sprites_tilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define sprites_tilesCGBPal3c0 32361
#define sprites_tilesCGBPal3c1 29576
#define sprites_tilesCGBPal3c2 8456
#define sprites_tilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define sprites_tilesCGBPal4c0 32361
#define sprites_tilesCGBPal4c1 20988
#define sprites_tilesCGBPal4c2 8456
#define sprites_tilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define sprites_tilesCGBPal5c0 6076
#define sprites_tilesCGBPal5c1 8935
#define sprites_tilesCGBPal5c2 6596
#define sprites_tilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define sprites_tilesCGBPal6c0 6076
#define sprites_tilesCGBPal6c1 8935
#define sprites_tilesCGBPal6c2 6596
#define sprites_tilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define sprites_tilesCGBPal7c0 6076
#define sprites_tilesCGBPal7c1 8935
#define sprites_tilesCGBPal7c2 6596
#define sprites_tilesCGBPal7c3 5344

/* Start of tile array. */
extern unsigned char sprites_tiles_compressed[];

/* End of TAKUZU_SPRITES.H */
