/*

 TAKUZU_BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\PC-Thibaut\Documents\GB_Dev\GBTD\takuzu_bg.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define takuzu_bgWidth 20
#define takuzu_bgHeight 18
#define takuzu_bgBank 0

#define takuzu_bg takuzu_bgPLN0
extern unsigned char takuzu_bg_top[];
extern unsigned char takuzu_bg_bot[];
extern unsigned char metasprite_tile[];
extern unsigned char takuzu_bg_center[];
extern unsigned char takuzu_bg_tubes_l0[];
extern unsigned char takuzu_bg_tubes_l1[];
extern unsigned char takuzu_bg_tubes_r0[];
extern unsigned char takuzu_bg_tubes_r1[];

/* End of TAKUZU_BG.H */
